### ISSUE TITLE
Getting an Error while starting fargate scraper

### ISSUE THREAD

**Issue by GoverningCloud** [Bogdanp/fargate_scraper#1]
I pip installed fargate-scraper , when I run the command to start it; fargate-scraper --cluster-name fargatecluster output.json , I get an invalid syntax error.

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/fargate-scraper", line 7, in <module>
    from fargate_scraper import main
  File "/home/ubuntu/.local/lib/python2.7/site-packages/fargate_scraper.py", line 34
    **kwargs,
     ^
SyntaxError: invalid syntax`

- I am using ubuntu 16.04 with python 3.6

**Comment by Bogdanp** [comment]
`"/home/ubuntu/.local/lib/python2.7/site-packages/fargate_scraper.py"`

Looks like you're using Python 2.7.

**Comment by Bogdanp** [comment]
Closing this for now. Let me know if you run into issues running it on python 3.
